black(X):-criminal(X).
black(p).
criminal(n).
male(jack).
male(oliver).
male(ali).
male(james).
male(simon).
male(harry).
female(helen).
female(sophie).
female(jess).
female(lily). 
parentOf(jack,jess).
parentOf(jack,lily).
parentOf(helen,jess).
parentOf(helen,lily).
parentOf(oliver,james).
parentOf(sophie,james).
parentOf(jess,simon).
parentOf(ali,simon).
parentOf(lily,harry).
parentOf(james,harry).
